#!/bin/bash

export WEBDRIVER_GECKO_DRIVER=/Users/fernandobrule/Clones/futurepyme/futurepyme-office/futurepyme-office-web-spa/node_modules/geckodriver/geckodriver
export WEBDRIVER_CHROME_DRIVER=/Users/fernandobrule/Clones/futurepyme/futurepyme-office/futurepyme-office-web-spa/node_modules/chromedriver/bin/chromedriver

./sbt -v -213
